"""E2E tests for audio separation endpoint."""

import pytest
import requests

from .config import REQUEST_TIMEOUT, SHORT_DURATION
from .conftest import validate_wav


# Public domain test audio URL (short sample)
# Using a well-known public domain audio source
TEST_AUDIO_URL = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"


class TestAudioSeparation:
    """Full E2E tests for /separate endpoint."""

    @pytest.mark.timeout(600)
    def test_separate_audio_from_url(
        self,
        session: requests.Session,
        api_url: str,
        auth_headers: dict,
        wait_for_job_completion,
        download,
    ):
        """Test separating audio from a URL into vocals and accompaniment."""
        # Submit separation request
        response = session.post(
            f"{api_url}/separate",
            json={"audio_url": TEST_AUDIO_URL},
            headers=auth_headers,
            timeout=REQUEST_TIMEOUT,
        )
        assert response.status_code == 200
        job_id = response.json()["job_id"]

        # Wait for completion (separation can take a while)
        result = wait_for_job_completion(job_id, timeout=300)
        assert result["status"] == "completed"
        assert result["result_urls"] is not None
        assert len(result["result_urls"]) == 2  # vocals + accompaniment

        # Download and validate both stems
        for url in result["result_urls"]:
            wav_data = download(url)
            props = validate_wav(wav_data)

            # Check valid WAV properties
            assert props["channels"] in [1, 2]
            assert props["framerate"] > 0
            assert props["duration"] > 0

    @pytest.mark.timeout(600)
    def test_separate_uses_generated_audio(
        self,
        session: requests.Session,
        api_url: str,
        auth_headers: dict,
        wait_for_job_completion,
        download,
    ):
        """Test separating audio that was generated by the API itself."""
        # First, generate some music
        gen_response = session.post(
            f"{api_url}/generate",
            json={
                "prompt": "pop song with vocals and guitar",
                "duration": SHORT_DURATION,
            },
            headers=auth_headers,
            timeout=REQUEST_TIMEOUT,
        )
        assert gen_response.status_code == 200
        gen_job_id = gen_response.json()["job_id"]

        # Wait for generation to complete
        gen_result = wait_for_job_completion(gen_job_id, timeout=180)
        assert gen_result["status"] == "completed"

        # Get the generated file URL
        generated_file_url = gen_result["result_urls"][0]

        # Now separate it using the full URL
        full_url = f"{api_url}{generated_file_url}"
        sep_response = session.post(
            f"{api_url}/separate",
            json={"audio_url": full_url},
            headers=auth_headers,
            timeout=REQUEST_TIMEOUT,
        )
        assert sep_response.status_code == 200
        sep_job_id = sep_response.json()["job_id"]

        # Wait for separation
        sep_result = wait_for_job_completion(sep_job_id, timeout=300)
        assert sep_result["status"] == "completed"
        assert len(sep_result["result_urls"]) == 2

    def test_separate_invalid_url(
        self,
        session: requests.Session,
        api_url: str,
        auth_headers: dict,
    ):
        """Test that separation fails gracefully with invalid URL."""
        response = session.post(
            f"{api_url}/separate",
            json={"audio_url": "https://invalid-domain-that-does-not-exist.com/audio.mp3"},
            headers=auth_headers,
            timeout=REQUEST_TIMEOUT,
        )
        # Should either fail validation or queue the job (which will fail)
        if response.status_code == 200:
            # Job was queued, check it fails
            job_id = response.json()["job_id"]
            import time

            for _ in range(30):
                status_response = session.get(
                    f"{api_url}/jobs/{job_id}",
                    timeout=REQUEST_TIMEOUT,
                )
                data = status_response.json()
                if data["status"] == "failed":
                    assert data["error"] is not None
                    break
                elif data["status"] == "completed":
                    pytest.fail("Job should have failed with invalid URL")
                time.sleep(2)

    def test_separate_progress_tracking(
        self,
        session: requests.Session,
        api_url: str,
        auth_headers: dict,
    ):
        """Test that separation progress can be tracked."""
        import time

        response = session.post(
            f"{api_url}/separate",
            json={"audio_url": TEST_AUDIO_URL},
            headers=auth_headers,
            timeout=REQUEST_TIMEOUT,
        )
        assert response.status_code == 200
        job_id = response.json()["job_id"]

        # Poll for status
        for _ in range(120):
            status_response = session.get(
                f"{api_url}/jobs/{job_id}",
                timeout=REQUEST_TIMEOUT,
            )
            assert status_response.status_code == 200
            data = status_response.json()

            assert data["job_id"] == job_id
            assert "status" in data
            assert "progress" in data

            if data["status"] in ["completed", "failed"]:
                break

            time.sleep(3)
