apiVersion: v1
kind: Service
metadata:
  name: musicgen
  namespace: musicgen
  labels:
    app: musicgen
spec:
  type: ClusterIP
  selector:
    app: musicgen
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
